# -*- coding: utf-8 -*-
"""Code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fXUeQANI_MPLydkazakx-tKJ5mkRBFsB
"""

import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
import pandas as pd

# Đọc dữ liệu từ file

df = pd.read_excel('/content/data-kmean.xlsx')

# Loại bỏ các hàng chứa dữ liệu bị thiếu
df_cleaned = df.dropna()

# Chuyển đổi DataFrame thành mảng NumPy
X = df_cleaned.values

# Tạo một từ điển rỗng để lưu tổng khoảng cách bình phương cho mỗi giá trị của k
sse = {}

# Fit KMeans cho một loạt các số lượng cụm
for k in range(1, 11):
    kmeans = KMeans(n_clusters=k, random_state=42)
    kmeans.fit(X)
    sse[k] = kmeans.inertia_

# Vẽ biểu đồ elbow
plt.figure(figsize=(8, 6))
plt.plot(list(sse.keys()), list(sse.values()), marker='o')
plt.xlabel('Số lượng cụm')
plt.ylabel('Tổng khoảng cách bình phương')
plt.title('Phương pháp Elbow để xác định k tối ưu')
plt.xticks(list(sse.keys()))
plt.grid(True)
plt.show()